// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmfSRDrhNAI95_rxzhKg_qwsbKM5tAEvc',
    appId: '1:576220469978:web:029024ef966c44b03de3e3',
    messagingSenderId: '576220469978',
    projectId: 'riderapp-1b828',
    authDomain: 'riderapp-1b828.firebaseapp.com',
    storageBucket: 'riderapp-1b828.appspot.com',
    measurementId: 'G-2S6RMGGNG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrrXcYSWzYecTD9mcl6ufpbooLEDBaIeY',
    appId: '1:576220469978:android:7aff0febb9e6abab3de3e3',
    messagingSenderId: '576220469978',
    projectId: 'riderapp-1b828',
    storageBucket: 'riderapp-1b828.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4MldIJQ_5ZROg6ERrERqWCOGV_rydw_Y',
    appId: '1:576220469978:ios:720269be371c2c7e3de3e3',
    messagingSenderId: '576220469978',
    projectId: 'riderapp-1b828',
    storageBucket: 'riderapp-1b828.appspot.com',
    iosBundleId: 'com.example.rideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4MldIJQ_5ZROg6ERrERqWCOGV_rydw_Y',
    appId: '1:576220469978:ios:720269be371c2c7e3de3e3',
    messagingSenderId: '576220469978',
    projectId: 'riderapp-1b828',
    storageBucket: 'riderapp-1b828.appspot.com',
    iosBundleId: 'com.example.rideApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmfSRDrhNAI95_rxzhKg_qwsbKM5tAEvc',
    appId: '1:576220469978:web:0ca403fd5acbd80a3de3e3',
    messagingSenderId: '576220469978',
    projectId: 'riderapp-1b828',
    authDomain: 'riderapp-1b828.firebaseapp.com',
    storageBucket: 'riderapp-1b828.appspot.com',
    measurementId: 'G-RPXDPXRN6F',
  );
}
